//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church_management_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class login_regtbl
    {
        public int userId { get; set; }

        [Required(ErrorMessage = "enter username", AllowEmptyStrings = false)]

        public string username { get; set; }
       
         [Required(ErrorMessage = "enter password", AllowEmptyStrings = false)]
        [StringLength(100,ErrorMessage ="must be at least 8 characters",MinimumLength =8)]
        public string password { get; set; }

       [Required(ErrorMessage = "confirm password", AllowEmptyStrings = false)]
        [Compare("password",ErrorMessage ="password did not match")]
        public string confirmpwd { get; set; }

    }
}
