//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church_management_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_Reg
    {
        public int FamilyNo { get; set; }
        public string WardName { get; set; }
        public int WardNumber { get; set; }
        public string FamilyName { get; set; }
        public string FamilyHead { get; set; }
        public string H_father_name { get; set; }
        public string H_mother_name { get; set; }
        public string H_wife_name { get; set; }
        public string W_familyName { get; set; }
        public string W_place { get; set; }
        public string W_parish { get; set; }
        public Nullable<int> Mob_nob { get; set; }
        public Nullable<int> Landline { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Town { get; set; }
        public string PO { get; set; }
        public string Landmark { get; set; }
        public string Prev_Parish { get; set; }
        public string Prev_Dioceses { get; set; }
        public string email { get; set; }
        public string Occupation { get; set; }
        public string MonthlyIncome { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase file { get; set; }
        public System.DateTime Time { get; set; }
    }
}
